_EMOJIS = [
    "\N{abacus}",
    "\N{airplane}",
    "\N{anchor}",
    "\N{aquarius}",
    "\N{aries}",
    "\N{axe}",
    "\N{balloon}",
    "\N{banana}",
    "\N{banjo}",
    "\N{baseball}",
    "\N{battery}",
    "\N{bed}",
    "\N{bell}",
    "\N{bikini}",
    "\N{blue heart}",
    "\N{bookmark}",
    "\N{books}",
    "\N{bowling}",
    "\N{brain}",
    "\N{broom}",
    "\N{butter}",
    "\N{butterfly}",
    "\N{cactus}",
    "\N{calendar}",
    "\N{candle}",
    "\N{candy}",
    "\N{carrot}",
    "\N{cat}",
    "\N{cityscape}",
    "\N{clipboard}",
    "\N{cloud}",
    "\N{coconut}",
    "\N{comet}",
    "\N{compass}",
    "\N{cow}",
    "\N{cupcake}",
    "\N{dango}",
    "\N{desert}",
    "\N{dog}",
    "\N{door}",
    "\N{dress}",
    "\N{dvd}",
    "\N{ear}",
    "\N{egg}",
    "\N{elephant}",
    "\N{elf}",
    "\N{envelope}",
    "\N{evergreen tree}",
    "\N{eyes}",
    "\N{factory}",
    "\N{fairy}",
    "\N{file folder}",
    "\N{fire}",
    "\N{fireworks}",
    "\N{foggy}",
    "\N{foot}",
    "\N{fork and knife}",
    "\N{fountain}",
    "\N{genie}",
    "\N{gorilla}",
    "\N{grapes}",
    "\N{green apple}",
    "\N{green heart}",
    "\N{guitar}",
    "\N{honey pot}",
    "\N{horse}",
    "\N{hospital}",
    "\N{ice cream}",
    "\N{key}",
    "\N{keyboard}",
    "\N{label}",
    "\N{leg}",
    "\N{lemon}",
    "\N{leo}",
    "\N{libra}",
    "\N{lollipop}",
    "\N{love letter}",
    "\N{mage}",
    "\N{magnet}",
    "\N{maple leaf}",
    "\N{merperson}",
    "\N{monkey}",
    "\N{mouse}",
    "\N{mushroom}",
    "\N{nose}",
    "\N{octopus}",
    "\N{onion}",
    "\N{orange heart}",
    "\N{package}",
    "\N{pager}",
    "\N{palm tree}",
    "\N{peach}",
    "\N{pencil}",
    "\N{pie}",
    "\N{pig}",
    "\N{pill}",
    "\N{pineapple}",
    "\N{police car}",
    "\N{poodle}",
    "\N{popcorn}",
    "\N{postbox}",
    "\N{potato}",
    "\N{printer}",
    "\N{purple heart}",
    "\N{rabbit}",
    "\N{raccoon}",
    "\N{radio}",
    "\N{rainbow}",
    "\N{raised hand}",
    "\N{ram}",
    "\N{receipt}",
    "\N{revolving hearts}",
    "\N{ribbon}",
    "\N{ring}",
    "\N{satellite}",
    "\N{scarf}",
    "\N{seat}",
    "\N{shamrock}",
    "\N{shield}",
    "\N{ship}",
    "\N{shorts}",
    "\N{shower}",
    "\N{shrimp}",
    "\N{sled}",
    "\N{snowman}",
    "\N{sparkle}",
    "\N{sparkles}",
    "\N{sparkling heart}",
    "\N{spoon}",
    "\N{stadium}",
    "\N{station}",
    "\N{statue of liberty}",
    "\N{strawberry}",
    "\N{taco}",
    "\N{tanabata tree}",
    "\N{taurus}",
    "\N{taxi}",
    "\N{tent}",
    "\N{thought balloon}",
    "\N{tiger}",
    "\N{tongue}",
    "\N{tooth}",
    "\N{train}",
    "\N{tropical fish}",
    "\N{trumpet}",
    "\N{umbrella}",
    "\N{vampire}",
    "\N{virgo}",
    "\N{waffle}",
    "\N{watch}",
    "\N{watermelon}",
    "\N{wedding}",
    "\N{whale}",
    "\N{white heart}",
    "\N{wrench}",
    "\N{yellow heart}",
    "\N{zombie}",
]